### PR TITLE
Update java, scala and sbt versions in travis and build files

### PR DESCRIPTION
**Pull request by wassertim**
I think it would be good if we update the versions of scala, java and everything ...

@BrandonArp please review

### CODE REVIEW

**Comment by wassertim** [comment]
Hey @BrandonArp, what do we need to do in order to make it work?

**Comment by BrandonArp** [comment]
One of the problems looks like jsengine releases.  We might need to get one of the typesafe guys to release it for sbt 13?  I'm not entirely sure, to be honest.  Have you gotten these to build locally?

As per https://docs.travis-ci.com/user/languages/java, it looks like Travis doesn't support openjdk8.  I'm fine with dropping jdk7 support altogether if that's required, but I don't think we've done anything that is only in java 8 yet.

There is some way to cross build scala versions.  I think I need to look into how to do that.

**Comment by wassertim** [comment]
I tested it locally and it works in the state I have committed (everything: the build and the tests).

Yes the sbt-js-engine seems to be a problem, because it does not have a scala 2.11 version. That's why I did not update the build version to scala 2.11.

That would be great if you look into it and tell what we can do and what we can't.

**Comment by wassertim** [comment]
Hey @BrandonArp !

Do you have any update on this? Maybe I can change something in the code?

**Comment by wassertim** [comment]
Hey. Any update on this?

**Comment by BrandonArp** [comment]
Sorry I dropped the ball on this. I'll try to get the Travis build figured out today.

**Pull request closed without merging**
