### PR TITLE
Upgrade typescript to 2.2.2

### PR DESCRIPTION
**Pull request by zy4**

### CODE REVIEW

**Comment by djx314** [comment]
https://github.com/Microsoft/TypeScript/tree/v2.3.0
ts 2.3.0 is out. What about upgrade to 2.3 ?

**Comment by zy4** [comment]
AFAIK, it's a prerelease: https://github.com/Microsoft/TypeScript/releases
And 2.2.2 should have no compatibility issues because it is only a bug-fixing release.
But sure, if nothing breaks, I would also go for 2.3!

**Comment by djx314** [comment]
The prerelease is v2.3-rc , 2.3.0 is anohter tag. But now the last release is 2.3.1 . So fast....

**Comment by BrandonArp** [comment]
Thanks for this PR.  I merged, updated to typescript 2.3.1, and released as 0.3.4.  You should find it in central now.

**Pull request merged**
